// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4p9KBC1GjebNzUFGklhzEDsZQnwAfKw',
    appId: '1:156566403222:web:5bdd5e66827effb73faab7',
    messagingSenderId: '156566403222',
    projectId: 'meserosapp-8af53',
    authDomain: 'meserosapp-8af53.firebaseapp.com',
    storageBucket: 'meserosapp-8af53.firebasestorage.app',
    measurementId: 'G-G0Y89P1YXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYMnCEQKnLUiZ8xc4ye9WQTcRTbQ-fouA',
    appId: '1:156566403222:android:dd0dcde9237f57ac3faab7',
    messagingSenderId: '156566403222',
    projectId: 'meserosapp-8af53',
    storageBucket: 'meserosapp-8af53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAKGkyyt1K2pCUNRMJKvq7ByXBJVaY5Dw',
    appId: '1:156566403222:ios:46314a63027397a13faab7',
    messagingSenderId: '156566403222',
    projectId: 'meserosapp-8af53',
    storageBucket: 'meserosapp-8af53.firebasestorage.app',
    iosBundleId: 'com.superlikers.meserosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAKGkyyt1K2pCUNRMJKvq7ByXBJVaY5Dw',
    appId: '1:156566403222:ios:46314a63027397a13faab7',
    messagingSenderId: '156566403222',
    projectId: 'meserosapp-8af53',
    storageBucket: 'meserosapp-8af53.firebasestorage.app',
    iosBundleId: 'com.superlikers.meserosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4p9KBC1GjebNzUFGklhzEDsZQnwAfKw',
    appId: '1:156566403222:web:41bb1fb784a3882d3faab7',
    messagingSenderId: '156566403222',
    projectId: 'meserosapp-8af53',
    authDomain: 'meserosapp-8af53.firebaseapp.com',
    storageBucket: 'meserosapp-8af53.firebasestorage.app',
    measurementId: 'G-5E9EL2T190',
  );
}
